---
title: "Habitat Bandwidth Calculations"
author: "B. Crary"
date: "January 18"
output: html_document
runtime: shiny
---

Creating a **Shiny** Application to visualize habitat conditions.

```{r setup, include=FALSE}
library(shiny)
library(ggplot2)
library(tidyr)
library(plyr)
library(quantmod)
library(shiny)

shift <- function(x, n){
  c(x[-(seq(n))], rep(0, n))
}

```



```{r echo=FALSE, warning=FALSE}

workspace <- "C:/Users/bcrary/Desktop/Temp/TDO3/Bandwith/"
inputfile <- "Profiles_toR.csv"

data <- read.csv(inputfile, header=TRUE)
data$ActivityID <- paste(data$Station,"-", data$Date)


#### Define Band Heights ####
activities <- levels(as.factor(data$ActivityID))
parameters <- levels(as.factor(data$Parameter))
stations <- levels(as.factor(data$Station))

inputPanel(
      fileInput('file1', 'Choose CSV File',
                accept=c('text/csv', 
								 'text/comma-separated-values,text/plain', 
								 '.csv')),
      checkboxInput('header', 'Header', TRUE),
      radioButtons('sep', 'Separator',
                   c(Comma=',',
                     Semicolon=';',
                     Tab='\t'),
                   ','),
      radioButtons('quote', 'Quote',
                   c(None='',
                     'Double Quote'='"',
                     'Single Quote'="'"),
                   '"')
)

flowLayout(
  selectInput("Sta", "Station", stations),
  sliderInput("DOval", "DO Minimum (mg/L):", min=2, max=6,value=6,step=0.25),
  sliderInput("Tempval","Temperature Maximum (Deg F)", min=58, max=70, value=66, step=1)
)

Act <- character(0)
Site <- character(0)
Param <- character(0)
Band <- numeric(0)
date <- character(0)



renderTable({
  
    for (activity in activities) {
        df <- subset(data, data$ActivityID == activity)
        for (parameter in parameters) {
          ds <- subset(df, df$Parameter == parameter)
          #ds <- subset(ds, ds$Depth_ft > 15)
          ds <- ddply(ds, "ActivityID", transform, DeltaCol = Delt(Value))
          ds$Delt.1.arithmetic <-shift(ds$Delt.1.arithmetic, 1)
          limit <- ifelse(parameter == "Temperature", input$Tempval, input$DOval)
          ds$diff <- ds$Value-limit
          high <- min(ds$diff[ds$diff > 0 & ds$Delt.1.arithmetic < 0])
          low <- max(ds$diff[ds$diff < 0])
          dth <- subset(ds, ds$diff == high)
          dth <- aggregate(Depth_ft~Date +Station+Parameter+Value+Units+ActivityID+diff, data=dth, FUN=max)
          dtl <- subset(ds, ds$diff == low)
          dtl <- aggregate(Depth_ft~Date+Station+Parameter+Value+Units+ActivityID+diff, data=dtl, FUN=min)
          dt <- rbind(dth,dtl)
          banddepth <- approx(dt$Value, dt$Depth_ft,limit)
          Act <- c(Act,dt$ActivityID[1])
          Site <- c(Site, as.character(dt$Station[1]))
          Param <- c(Param, parameter)
          Band <- c(Band, banddepth$y[1])
          date <- c(date, as.character(dt$Date[1]))
        }
      }

  
      date <- as.POSIXct(date, format = "%m/%d/%Y")
      dt.summary <- data.frame(Act, Site, date, Param, Band)
      dt.summary <- aggregate(Band ~ Act+Site+date, FUN=function(x){y <- diff(x*-1)/3.2808; return(y)})
      dt.summary$Bandwidth_m <- ifelse(dt.summary$Band>0,dt.summary$Band, 0)
      dx <- reactive({subset(dt.summary, dt.summary$Site == input$Sta)})
      dx()

    })




renderPlot({
        for (activity in activities) {
        df <- subset(data, data$ActivityID == activity)
        for (parameter in parameters) {
        ds <- subset(df, df$Parameter == parameter)
        #ds <- subset(ds, ds$Depth_ft > 15)
        ds <- ddply(ds, "ActivityID", transform, DeltaCol = Delt(Value))
        ds$Delt.1.arithmetic <-shift(ds$Delt.1.arithmetic, 1)
        limit <- ifelse(parameter == "Temperature", input$Tempval, input$DOval)
        ds$diff <- ds$Value-limit
        high <- min(ds$diff[ds$diff > 0 & ds$Delt.1.arithmetic < 0])
        low <- max(ds$diff[ds$diff < 0])
        dth <- subset(ds, ds$diff == high)
        dth <- aggregate(Depth_ft~Date +Station+Parameter+Value+Units+ActivityID+diff, data=dth, FUN=max)
        dtl <- subset(ds, ds$diff == low)
        dtl <- aggregate(Depth_ft~Date+Station+Parameter+Value+Units+ActivityID+diff, data=dtl, FUN=min)
        dt <- rbind(dth,dtl)
        banddepth <- approx(dt$Value, dt$Depth_ft,limit)
        Act <- c(Act,dt$ActivityID[1])
        Site <- c(Site, as.character(dt$Station[1]))
        Param <- c(Param, parameter)
        Band <- c(Band, banddepth$y[1])
        date <- c(date, as.character(dt$Date[1]))
      }
    }
  
    date <- as.POSIXct(date, format = "%m/%d/%Y")
    dt.summary <- data.frame(Act, Site, date, Param, Band)
    dt.summary <- aggregate(Band ~ Act+Site+date, FUN=function(x){y <- diff(x*-1)/3.2808; return(y)})
    dt.summary$Bandwidth_m <- ifelse(dt.summary$Band>0,dt.summary$Band, 0)
  
    dz <- reactive({subset(dt.summary, dt.summary$Site == input$Sta)})
    plotheight <- ifelse(max(dz()$Bandwidth_m) >2, ceiling(max(dz()$Bandwidth_m)),2)
    p1 <- ggplot(dz(), aes(x=as.factor(dz()$date), y=dz()$Bandwidth_m)) +
    geom_bar(stat="identity", fill="steelblue")  + 
    xlab("") +
    ylab("Depth of Habitat Band (meters)") +
    ylim(0,plotheight) + 
    geom_hline(yintercept=1, linetype=2) +
    theme_minimal() +
    theme(panel.background=element_rect(colour="white"),
          axis.text = element_text(size=12), 
          panel.grid = element_blank()
      )
    p1
  })


```

<br>
<br>
Temperature and Dissolve Oxygen Profiles:
<br>

```{r echo=FALSE, warning=FALSE}
data <- read.csv(inputfile, header=TRUE)
data$ActivityID <- paste(data$Station,"-", data$Date)

renderPlot({
      data.p2 <- reactive({subset(data, data$Station == input$Sta)})
      p2 <- ggplot(data.p2(), aes(x=data.p2()$Value,y=data.p2()$Depth_ft/3.2808*-1)) +
        geom_point(aes(colour=data.p2()$Parameter)) +
        scale_colour_manual(values=c("steelblue", "firebrick3")) +
        ylab("Depth (meters)") +
        xlab("Value") +
        facet_grid(data.p2()$Parameter~data.p2()$Date, scale="free_x") +
        theme_minimal() +
        theme(panel.background=element_rect(colour="grey80", fill="gray98"),
          axis.text = element_text(size=12), 
          panel.grid = element_blank()
      )
      p2
  })
    
```


